apiVersion: v1 # Each API vversion defines a different set of 'objects' we can use
kind: Pod # running a container
metadata:
  name: client
  labels:
    component: web
spec:
  containers:
    - name: client
      image: saikat/multi-client
      ports:
        - containerPort: 3000
