apiVersion: v1
kind: Service # setting up networking
medata:
  name: client-node-port
spec:
  type: NodePort
  ports:
    - ports: 3050
    targetPort: 3000
    nodePort: 31515
  selector:
    component: Web
